use serde_json::json;

use crate::domain::exports::CreateExportTemplate;
use crate::errors::AppError;

const BIND_FORWARD_ZONE_TEMPLATE: &str = r#"; Zone file for {{ zone.name }}
; Generated by mreg-rust
$ORIGIN {{ zone.name }}.
$TTL {{ zone.default_ttl }}

; SOA record
@ {{ zone.soa_ttl }} IN SOA {{ zone.primary_ns }}. {{ zone.email | replace("@", ".") }}. (
    {{ zone.serial_no }}  ; serial
    {{ zone.refresh }}     ; refresh
    {{ zone.retry }}       ; retry
    {{ zone.expire }}      ; expire
    {{ zone.soa_ttl }}     ; minimum TTL
)

; Records
{% for record in records %}
{% set owner = record.owner_name %}
{% if owner == zone.name %}{% set owner = "@" %}{% endif %}
{{ owner }}{% if owner != "@" %}.{% endif %} {{ record.ttl | default(value=zone.default_ttl) }} IN {{ record.type_name }} {{ record.rendered }}
{% endfor %}
"#;

const BIND_REVERSE_ZONE_TEMPLATE: &str = r#"; Reverse zone file for {{ zone.name }}
; Generated by mreg-rust
$ORIGIN {{ zone.name }}.
$TTL {{ zone.default_ttl }}

; SOA record
@ {{ zone.soa_ttl }} IN SOA {{ zone.primary_ns }}. {{ zone.email | replace("@", ".") }}. (
    {{ zone.serial_no }}  ; serial
    {{ zone.refresh }}     ; refresh
    {{ zone.retry }}       ; retry
    {{ zone.expire }}      ; expire
    {{ zone.soa_ttl }}     ; minimum TTL
)

; Records
{% for record in records %}
{{ record.owner_name }}. {{ record.ttl | default(value=zone.default_ttl) }} IN {{ record.type_name }} {{ record.rendered }}
{% endfor %}
"#;

const KEA_DHCP4_FRAGMENT_TEMPLATE: &str = r#"[
{% for network in dhcp4_networks %}
  {
    "subnet": "{{ network.cidr }}",
    "reservations": [
{% for attachment in network.dhcp4_attachments %}
      {
{% if attachment.matchers.ipv4.kind == "client_id" %}
        "client-id": "{{ attachment.matchers.ipv4.value }}",
{% else %}
        "hw-address": "{{ attachment.matchers.ipv4.value }}",
{% endif %}
        "hostname": "{{ attachment.host_name }}",
        "ip-address": "{{ attachment.primary_ipv4_address }}"
      }{% if not loop.last %},{% endif %}
{% endfor %}
    ]
  }{% if not loop.last %},{% endif %}
{% endfor %}
]"#;

const KEA_DHCP4_FULL_TEMPLATE: &str = r#"{
  "Dhcp4": {
    "interfaces-config": {
      "interfaces": []
    },
    "subnet4": [
{% for network in dhcp4_networks %}
      {
        "subnet": "{{ network.cidr }}",
        "reservations": [
{% for attachment in network.dhcp4_attachments %}
          {
{% if attachment.matchers.ipv4.kind == "client_id" %}
            "client-id": "{{ attachment.matchers.ipv4.value }}",
{% else %}
            "hw-address": "{{ attachment.matchers.ipv4.value }}",
{% endif %}
            "hostname": "{{ attachment.host_name }}",
            "ip-address": "{{ attachment.primary_ipv4_address }}"
          }{% if not loop.last %},{% endif %}
{% endfor %}
        ]
      }{% if not loop.last %},{% endif %}
{% endfor %}
    ]
  }
}"#;

const KEA_DHCP6_FRAGMENT_TEMPLATE: &str = r#"[
{% for network in dhcp6_networks %}
  {
    "subnet": "{{ network.cidr }}",
    "reservations": [
{% for attachment in network.dhcp6_attachments %}
      {
        "duid": "{{ attachment.matchers.ipv6.value }}",
        "hostname": "{{ attachment.host_name }}"{% if attachment.primary_ipv6_address %},
        "ip-addresses": ["{{ attachment.primary_ipv6_address }}"]{% endif %}{% if attachment.prefix_reservations %},
        "prefixes": [{% for prefix in attachment.prefix_reservations %}"{{ prefix.prefix }}"{% if not loop.last %}, {% endif %}{% endfor %}]{% endif %}
      }{% if not loop.last %},{% endif %}
{% endfor %}
    ]
  }{% if not loop.last %},{% endif %}
{% endfor %}
]"#;

const KEA_DHCP6_FULL_TEMPLATE: &str = r#"{
  "Dhcp6": {
    "interfaces-config": {
      "interfaces": []
    },
    "subnet6": [
{% for network in dhcp6_networks %}
      {
        "subnet": "{{ network.cidr }}",
        "reservations": [
{% for attachment in network.dhcp6_attachments %}
          {
            "duid": "{{ attachment.matchers.ipv6.value }}",
            "hostname": "{{ attachment.host_name }}"{% if attachment.primary_ipv6_address %},
            "ip-addresses": ["{{ attachment.primary_ipv6_address }}"]{% endif %}{% if attachment.prefix_reservations %},
            "prefixes": [{% for prefix in attachment.prefix_reservations %}"{{ prefix.prefix }}"{% if not loop.last %}, {% endif %}{% endfor %}]{% endif %}
          }{% if not loop.last %},{% endif %}
{% endfor %}
        ]
      }{% if not loop.last %},{% endif %}
{% endfor %}
    ]
  }
}"#;

const ISC_DHCPD4_FRAGMENT_TEMPLATE: &str = r#"{% for network in dhcp4_networks %}
# {{ network.cidr }} {{ network.description }}
{% for attachment in network.dhcp4_attachments %}
host {{ attachment.host_name | replace(".", "-") }} {
  option host-name "{{ attachment.host_name }}";
{% if attachment.matchers.ipv4.kind == "client_id" %}
  option dhcp-client-identifier "{{ attachment.matchers.ipv4.value }}";
{% else %}
  hardware ethernet {{ attachment.matchers.ipv4.value }};
{% endif %}
  fixed-address {{ attachment.primary_ipv4_address }};
}

{% endfor %}
{% endfor %}"#;

const ISC_DHCPD4_FULL_TEMPLATE: &str = r#"# Generated by mreg-rust
authoritative;

{% for network in dhcp4_networks %}
# {{ network.cidr }} {{ network.description }}
{% for attachment in network.dhcp4_attachments %}
host {{ attachment.host_name | replace(".", "-") }} {
  option host-name "{{ attachment.host_name }}";
{% if attachment.matchers.ipv4.kind == "client_id" %}
  option dhcp-client-identifier "{{ attachment.matchers.ipv4.value }}";
{% else %}
  hardware ethernet {{ attachment.matchers.ipv4.value }};
{% endif %}
  fixed-address {{ attachment.primary_ipv4_address }};
}

{% endfor %}
{% endfor %}"#;

const ISC_DHCPD6_FRAGMENT_TEMPLATE: &str = r#"{% for network in dhcp6_networks %}
# {{ network.cidr }} {{ network.description }}
{% for attachment in network.dhcp6_attachments %}
host {{ attachment.host_name | replace(".", "-") }} {
  option host-name "{{ attachment.host_name }}";
  host-identifier option dhcp6.client-id {{ attachment.matchers.ipv6.value }};
{% if attachment.primary_ipv6_address %}
  fixed-address6 {{ attachment.primary_ipv6_address }};
{% endif %}
{% for prefix in attachment.prefix_reservations %}
  fixed-prefix6 {{ prefix.prefix }};
{% endfor %}
}

{% endfor %}
{% endfor %}"#;

const ISC_DHCPD6_FULL_TEMPLATE: &str = r#"# Generated by mreg-rust

{% for network in dhcp6_networks %}
# {{ network.cidr }} {{ network.description }}
{% for attachment in network.dhcp6_attachments %}
host {{ attachment.host_name | replace(".", "-") }} {
  option host-name "{{ attachment.host_name }}";
  host-identifier option dhcp6.client-id {{ attachment.matchers.ipv6.value }};
{% if attachment.primary_ipv6_address %}
  fixed-address6 {{ attachment.primary_ipv6_address }};
{% endif %}
{% for prefix in attachment.prefix_reservations %}
  fixed-prefix6 {{ prefix.prefix }};
{% endfor %}
}

{% endfor %}
{% endfor %}"#;

/// Returns the built-in export template definitions.
pub fn built_in_export_templates() -> Result<Vec<(CreateExportTemplate, bool)>, AppError> {
    Ok(vec![
        (
            CreateExportTemplate::new(
                "bind-forward-zone",
                "BIND zone file for a forward zone",
                "minijinja",
                "forward_zone",
                BIND_FORWARD_ZONE_TEMPLATE,
                json!({}),
            )?,
            true,
        ),
        (
            CreateExportTemplate::new(
                "bind-reverse-zone",
                "BIND zone file for a reverse zone",
                "minijinja",
                "reverse_zone",
                BIND_REVERSE_ZONE_TEMPLATE,
                json!({}),
            )?,
            true,
        ),
        (
            CreateExportTemplate::new(
                "dhcp-canonical-json",
                "Canonical attachment-centric DHCP export JSON",
                "json",
                "dhcp",
                "{}",
                json!({}),
            )?,
            true,
        ),
        (
            CreateExportTemplate::new(
                "kea-dhcp4-fragment",
                "Kea DHCPv4 reservation fragment",
                "minijinja",
                "dhcp",
                KEA_DHCP4_FRAGMENT_TEMPLATE,
                json!({}),
            )?,
            true,
        ),
        (
            CreateExportTemplate::new(
                "kea-dhcp4-full",
                "Kea DHCPv4 full configuration wrapper",
                "minijinja",
                "dhcp",
                KEA_DHCP4_FULL_TEMPLATE,
                json!({}),
            )?,
            true,
        ),
        (
            CreateExportTemplate::new(
                "kea-dhcp6-fragment",
                "Kea DHCPv6 reservation fragment",
                "minijinja",
                "dhcp",
                KEA_DHCP6_FRAGMENT_TEMPLATE,
                json!({}),
            )?,
            true,
        ),
        (
            CreateExportTemplate::new(
                "kea-dhcp6-full",
                "Kea DHCPv6 full configuration wrapper",
                "minijinja",
                "dhcp",
                KEA_DHCP6_FULL_TEMPLATE,
                json!({}),
            )?,
            true,
        ),
        (
            CreateExportTemplate::new(
                "isc-dhcpd4-fragment",
                "ISC DHCPv4 reservation fragment",
                "minijinja",
                "dhcp",
                ISC_DHCPD4_FRAGMENT_TEMPLATE,
                json!({}),
            )?,
            true,
        ),
        (
            CreateExportTemplate::new(
                "isc-dhcpd4-full",
                "ISC DHCPv4 full configuration wrapper",
                "minijinja",
                "dhcp",
                ISC_DHCPD4_FULL_TEMPLATE,
                json!({}),
            )?,
            true,
        ),
        (
            CreateExportTemplate::new(
                "isc-dhcpd6-fragment",
                "ISC DHCPv6 reservation fragment",
                "minijinja",
                "dhcp",
                ISC_DHCPD6_FRAGMENT_TEMPLATE,
                json!({}),
            )?,
            true,
        ),
        (
            CreateExportTemplate::new(
                "isc-dhcpd6-full",
                "ISC DHCPv6 full configuration wrapper",
                "minijinja",
                "dhcp",
                ISC_DHCPD6_FULL_TEMPLATE,
                json!({}),
            )?,
            true,
        ),
    ])
}
